from pathlib import Path
p=Path('index.html'); s=p.read_text(encoding='utf-8')
s=s.replace('width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover','width=device-width, initial-scale=1, viewport-fit=cover')
s=s.replace('maximum-scale=1, ','')
s=s.replace("!key.includes('v2.1.6.11')","!key.includes('v2.3.0')")
s=s.replace('Breizh’ Balade V2.1.6.11 — Application pour découvrir les plus beaux lieux, balades nature, plages, forêts et monuments historiques de Bretagne.','Breizh’ Balade V2.3.0 — 71 lieux, balades nature, patrimoine, plages, forêts et découvertes en Bretagne.')
s=s.replace('Breizh’ Balade V2.1.6.11 — by cr3@tix dev’','Breizh’ Balade V2.3.0 — by cr3@tix dev’').replace('21611','230')
meta='''  <link rel="canonical" href="https://kevinlabens-del.github.io/breizh-balade/" />\n  <meta property="og:type" content="website" />\n  <meta property="og:locale" content="fr_FR" />\n  <meta property="og:title" content="Breizh’ Balade — 71 idées de sorties en Bretagne" />\n  <meta property="og:description" content="Explore 71 lieux bretons : mer, forêt, patrimoine, villages, îles, balades et spots photo." />\n  <meta property="og:url" content="https://kevinlabens-del.github.io/breizh-balade/" />\n  <meta property="og:image" content="https://kevinlabens-del.github.io/breizh-balade/assets/icons/icon-512.png" />\n  <meta name="twitter:card" content="summary" />\n  <meta name="apple-mobile-web-app-capable" content="yes" />\n'''
if '<link rel="canonical"' not in s: s=s.replace('  <meta name="theme-color" content="#fff8ed" />\n','  <meta name="theme-color" content="#fff8ed" />\n'+meta,1)
for view in ('explore','map','about'): s=s.replace(f'data-view="{view}" data-access="private"',f'data-view="{view}" data-access="public"')
s=s.replace('Compte local non connecté','Navigation libre • compte optionnel')
s=s.replace('<section class="view" id="view-explore">','<section class="view is-visible" id="view-explore">',1).replace('<section class="view is-visible" id="view-login">','<section class="view" id="view-login">',1)
s=s.replace('<strong>Accès protégé</strong>\n          <span>Connecte-toi ou crée un compte local pour accéder à Breizh’ Balade.</span>','<strong>Compte optionnel</strong>\n          <span>Explorer et la carte sont accessibles sans compte. Connecte-toi seulement pour enregistrer tes favoris, notes et listes personnelles.</span>')
s=s.replace('Cette page permet de tester la connexion sans serveur. Le compte reste enregistré uniquement dans ce navigateur.','Compte local facultatif : il sert uniquement à conserver tes favoris, notes et listes sur cet appareil et dans ce navigateur.')
s=s.replace('<button class="oauth-btn" type="button" data-oauth="google">🔴 Continuer avec Google</button>','<button class="oauth-btn" type="button" disabled aria-disabled="true">🔴 Google — bientôt disponible</button>').replace('<button class="oauth-btn" type="button" data-oauth="facebook">🔵 Continuer avec Facebook</button>','<button class="oauth-btn" type="button" disabled aria-disabled="true">🔵 Facebook — bientôt disponible</button>')
s=s.replace('Mode test : ces boutons sont préparés visuellement. Ils fonctionneront réellement avec Firebase, Supabase ou un serveur sécurisé.','Connexion Google/Facebook non disponible dans cette version.')
s=s.replace('minlength="4"','minlength="8"').replace('4 caractères minimum','8 caractères minimum')
s=s.replace('Données de marée calculées via api-maree.fr, à partir de composantes harmoniques issues de l’atlas Ifremer / PREVIMER.','Estimation locale indicative des marées. Vérifie toujours les horaires officiels avant une sortie littorale.')
s=s.replace('V2.1.6.11','V2.3.0').replace('v2.1.6.11','v2.3.0')
p.write_text(s,encoding='utf-8')
